version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: postgres-db

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-app:
    image: payment-service:v3
    container_name: payment-app

    ports:
      - "8080:8080"

    depends_on:
      - postgres

volumes:
  postgres_data: